config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    resource :qr_code, only: [:show]
    get '/generate_qr_code', to: 'generate_qr_code#generate_qr_code', as: 'generate_qr_code'
  end

  # For user login
  devise_for :users, controllers: { sessions: 'users/sessions' }

  # For admin login
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root to: 'landing_page#index'

  resources :memberships, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :orders, only: [:show, :create]
  resources :payments, only: :new

  get '/home', to: 'pages#home'
  get '/memberships', to: 'pages#memberships'
  get '/book_a_private_class', to: 'pages#book_a_private_class'
  get '/mejiro_coin', to: 'pages#mejiro_coin'
  get '/payment_scanner', to: 'pages#payment_scanner'
  get '/weekly_class_schedule', to: 'pages#weekly_class_schedule'
  get '/events', to: 'pages#events'
  get '/qr_code_scanner', to: 'pages#qr_code_scanner'
  get '/membership_details', to: 'pages#membership_details', as: 'membership_details'
  get "/products/:id", to: "pages#show_product"
  post "/products/:id", to: "pages#purchase_product", as: "purchase_product"
  get '/membership/:id/checkout', to: 'pages#membership_checkout', as: 'membership_checkout'
  get '/top_up', to: 'top_ups#index', as: 'top_ups'
  get '/top_up/:id/success', to: 'top_ups#show_success', as: 'top_up_success'
  get '/top_up/:id/failure', to: 'top_ups#show_failure', as: 'top_up_failure'
  get '/top_up/checkout/:amount', to: 'top_ups#checkout', as: 'top_up_checkout'
  get '/qr_code_info', to: 'qr_code_info#show', as: 'qr_code_info'

  resources :orders do
    get 'new_payment', to: 'payments#new', as: 'new_payment'
  end

  get 'go_back', to: 'pages#home'

  devise_scope :user do
    delete 'users/sign_out', to: 'users/sessions#destroy', as: :user_sign_out
  end

  devise_scope :admin do
    delete 'admins/sign_out', to: 'admins/sessions#destroy', as: :admin_sign_out
  end

  namespace :pages do
    get 'memberships', to: 'memberships#index'
  end

  namespace :admins do
    resources :users, only: [:destroy] # Restrict user deletion to admins
    resources :memberships do
      post 'add_days', on: :member
      post 'add_or_remove_membership_types', on: :collection
      post 'create_or_remove_membership', on: :collection
    end

    resources :weekly_class_schedule, only: [:index, :new, :create, :edit, :update, :destroy] do
      get 'new_weekly_class_schedule', to: 'weekly_class_schedule#new', as: 'new_weekly_class_schedule'
    end

    resources :membership_types, only: [:new, :create]
    post 'create_or_remove_membership', to: 'memberships#create_or_remove_membership', as: 'create_or_remove_membership'
    get 'dashboard/index', as: 'dashboard_index'
    get '/qr_code_information', to: 'member_qr_code_information#show', as: 'qr_code_information'
    resources :products, path: 'products'
    get 'mejiro_coin/admin', to: 'mejiro_coin#index', as: 'mejiro_coin_records'
    post 'mejiro_coin/add_credit', to: 'mejiro_coin#add_credit', as: 'add_credit_to_user'
    get 'memberships/show', as: 'show_membership'
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :category
  belongs_to :user, optional: true
  monetize :price_cents
  #has_many :orders, dependent: :destroy

  validates :days_of_membership, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true
  validates :category, presence: true
end

app/controllers/admins/memberships_controller.rb
class Admins::MembershipsController < AdminController
  def index
    @users_with_memberships = User.all.order(sort_column + ' ' + sort_direction)
  end

  def show
    # Retrieve all users and their memberships
    @users_with_memberships = User.all.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
  end

  # Controller action
  def new
    @membership = Membership.new
    @memberships = Membership.all
  end


  def create
    @membership = Membership.new(membership_params)
    if @membership.save
      flash[:success] = "Membership created successfully."
      redirect_to admins_memberships_path
    else
      flash[:error] = "Failed to create membership."
      render :new
    end
  end

  def membership_params
    params.require(:membership).permit(:name, :sku, :category_id, :price_cents, :days_of_membership)
  end

    def add_or_remove_membership_types
      if params[:action_type] == "add"
        # Logic to add a new membership type
        membership_params = {
          sku: params[:sku],
          name: params[:name],
          category: params[:category],
          price_cents: params[:price_cents],
          days_of_membership: params[:days_of_membership]
        }
        @membership = Membership.new(membership_params)

        if @membership.save
          flash[:success] = "Membership type added successfully."
        else
          flash[:error] = "Failed to add membership type."
        end
      elsif params[:action_type] == "remove"
        # Logic to remove an existing membership type
        membership = Membership.find_by(id: params[:membership_id])
        if membership.present?
          membership.destroy
          flash[:success] = "Membership type removed successfully."
        else
          flash[:error] = "Membership type not found."
        end
      end

      redirect_to admins_show_membership_path

    end


    def add_days
      user = User.find_by(id: params[:user_id])
      membership = Membership.find_by(id: params[:membership_id])

      if user.nil?
        flash[:error] = "User not found."
        redirect_to admins_memberships_show_path and return
      end

      if membership.nil?
        flash[:error] = "Membership not found."
        redirect_to admins_memberships_show_path and return
      end

      days_remaining = user.membership_days || 0
      days_to_modify = 0

      case membership.sku
      when "daily"
        days_to_modify += params[:order_amount].to_i
      when "monthly"
        days_to_modify += params[:order_amount].to_i * 30
      when "yearly"
        days_to_modify += params[:order_amount].to_i * 365
      end

      new_days = if params[:action_type] == "add"
                   days_remaining + days_to_modify
                 elsif params[:action_type] == "subtract"
                   [0, days_remaining - days_to_modify].max
                 else
                   flash[:error] = "Invalid action type."
                   redirect_to admins_memberships_show_path and return
                 end

      membership_log = user.membership_logs.create(
        membership_id: params[:membership_id],
        amount: params[:order_amount].to_i,
        total_cost: params[:total_cost].to_i,
        operation: params[:action_type]
      )

      user.last_membership_start_date = DateTime.now if user.membership_days_remaining == 0
      user.membership_days = new_days

      if user.memberships.exclude?(membership)
        user.memberships << membership
      end

      if user.save
        membership_log.save!
        flash[:success] = "#{days_to_modify} days #{params[:action_type]}ed successfully."
      else
        flash[:error] = "Failed to #{params[:action_type]} days."
      end

      redirect_to admins_show_membership_path(user_id: user.id)
    end




  private

  def sort_column
    params[:sort] || 'username'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    @memberships = Membership.includes(:user)
  end

  def show
    @membership = Membership.find(params[:id])
  end

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/index.html.erb
<section class="mx-auto max-w-screen-2xl px-4 py-4 sm:px-6 lg:px-8">
  <div class="shadow-lg bg-white p-6 rounded-lg">
        <div class="flex flex-col rounded-lg border border-red-900 px-4 py-8 text-center">
    <h1 class="text-2xl text-center py-2 font-bold text-gray-900 sm:text-3xl">Memberships</h1>
    <p class="mt-4 text-gray-500 sm:text-xl text-center">
      Monthly memberships can now be purchased at reception. When purchased, 30 membership days will automatically be added to your user account.
    </p>
  </div>

<div class="mx-auto max-w-screen-2xl px-4 py-4 sm:px-6 lg:px-8">
<div class="flex justify-center">
  <div class="max-w-screen-xl mx-auto mt-8 sm:mt-12">
    <div class="gap-4">
      <div class="flex flex-col rounded-lg border border-red-900 px-2 py-8 text-center mx-4">
        <%= cl_image_tag("https://res.cloudinary.com/dh8uxggfc/image/upload/v1714978044/Membership_prices_qxdrsx.jpg", width: 360, height: 450) %>
      </div>
    </div>
  </div>
</div>

</section>






<%#
<div class="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
  <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 sm:items-center md:gap-8">
    <% @memberships.each do |membership| %>
      <%# <div class="rounded-2xl border border-indigo-600 p-6 shadow-sm sm:px-8 lg:p-12">
        <div class="text-center">
          <h2 class="text-lg font-medium text-gray-900">
            <%= membership.name %>
            <%# <span class="sr-only">Plan</span>
          </h2>
          <p class="mt-2 sm:mt-4">
            <strong class="text-3xl font-bold text-gray-900 sm:text-4xl"><%= humanized_money_with_symbol(membership.price) %></strong>
            <%# <span class="text-sm font-medium text-gray-700">/month</span>
          </p>
        </div>
        <ul class="mt-6 space-y-2">
          <li class="flex items-center gap-1">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="h-5 w-5 text-indigo-700"
            >
              <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
            </svg>
            <span class="text-gray-700"></span>
          </li>
          <!-- Add more list items based on your needs -->
        </ul>
        <a
          href="<%= membership_path(membership) %>
          <%# class="mt-8 block rounded-full border border-indigo-600 bg-indigo-600 px-12 py-3 text-center text-sm font-medium text-white hover:bg-indigo-700 hover:ring-1 hover:ring-indigo-700 focus:outline-none focus:ring active:text-indigo-500"
        >
          Get Started
        </a>
      </div>
    <% end %>
  <%# </div>
</div>  %>

app/views/memberships/show.html.erb
<div class="container">
  <h1>Membership</h1>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <%= image_tag(@membership.photo_url, width: '100%') %>
    </div>
    <div class="col-sm-12 col-md-6">
      <h1><%= @membership.name %></h1>
      <p>Some description of our memberships.</p>
      <p>Amount: <%= humanized_money_with_symbol(@membership.price) %></p>
      <div class="btn btn-primary">
  <a href="/membership/<%= @membership.id %>/checkout" data-turbo="false" class="btn-primary-font">Purchase</a>
</div>
  </div>
    </div>
  </div>
</div>