config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    resource :qr_code, only: [:show]
    get '/generate_qr_code', to: 'generate_qr_code#generate_qr_code', as: 'generate_qr_code'
  end

  # For user login
  devise_for :users, controllers: { sessions: 'users/sessions' }

  # For admin login
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root to: 'landing_page#index'

  resources :memberships, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :orders, only: [:show, :create]
  resources :payments, only: :new

  get '/home', to: 'pages#home'
  get '/memberships', to: 'pages#memberships'
  get '/book_a_private_class', to: 'pages#book_a_private_class'
  get '/mejiro_coin', to: 'pages#mejiro_coin'
  get '/payment_scanner', to: 'pages#payment_scanner'
  get '/weekly_class_schedule', to: 'pages#weekly_class_schedule'
  get '/events', to: 'pages#events'
  get '/qr_code_scanner', to: 'pages#qr_code_scanner'
  get '/membership_details', to: 'pages#membership_details', as: 'membership_details'
  get "/products/:id", to: "pages#show_product"
  post "/products/:id", to: "pages#purchase_product", as: "purchase_product"
  get '/membership/:id/checkout', to: 'pages#membership_checkout', as: 'membership_checkout'
  get '/top_up', to: 'top_ups#index', as: 'top_ups'
  get '/top_up/:id/success', to: 'top_ups#show_success', as: 'top_up_success'
  get '/top_up/:id/failure', to: 'top_ups#show_failure', as: 'top_up_failure'
  get '/top_up/checkout/:amount', to: 'top_ups#checkout', as: 'top_up_checkout'
  get '/qr_code_info', to: 'qr_code_info#show', as: 'qr_code_info'

  resources :orders do
    get 'new_payment', to: 'payments#new', as: 'new_payment'
  end

  get 'go_back', to: 'pages#home'

  devise_scope :user do
    delete 'users/sign_out', to: 'users/sessions#destroy', as: :user_sign_out
  end

  devise_scope :admin do
    delete 'admins/sign_out', to: 'admins/sessions#destroy', as: :admin_sign_out
  end

  namespace :pages do
    get 'memberships', to: 'memberships#index'
  end

  namespace :admins do
    resources :users, only: [:destroy] # Restrict user deletion to admins
    resources :memberships do
      post 'add_days', on: :member
      post 'add_or_remove_membership_types', on: :collection
      post 'create_or_remove_membership', on: :collection
    end

    resources :weekly_class_schedule, only: [:index, :new, :create, :edit, :update, :destroy] do
      get 'new_weekly_class_schedule', to: 'weekly_class_schedule#new', as: 'new_weekly_class_schedule'
    end

    resources :membership_types, only: [:new, :create]
    post 'create_or_remove_membership', to: 'memberships#create_or_remove_membership', as: 'create_or_remove_membership'
    get 'dashboard/index', as: 'dashboard_index'
    get '/qr_code_information', to: 'member_qr_code_information#show', as: 'qr_code_information'
    resources :products, path: 'products'
    get 'mejiro_coin/admin', to: 'mejiro_coin#index', as: 'mejiro_coin_records'
    post 'mejiro_coin/add_credit', to: 'mejiro_coin#add_credit', as: 'add_credit_to_user'
    get 'memberships/show', as: 'show_membership'
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :category
  belongs_to :user, optional: true
  monetize :price_cents
  #has_many :orders, dependent: :destroy

  validates :days_of_membership, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true
  validates :category, presence: true
end

app/controllers/admins/memberships_controller.rb
class Admins::MembershipsController < AdminController
  def index
    @users_with_memberships = User.all.order(sort_column + ' ' + sort_direction)
  end

  def show
    # Retrieve all users and their memberships
    @users_with_memberships = User.all.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
  end

  # Controller action
  def new
    @membership = Membership.new
    @memberships = Membership.all
  end


  def create
    @membership = Membership.new(membership_params)
    if @membership.save
      flash[:success] = "Membership created successfully."
      redirect_to admins_memberships_path
    else
      flash[:error] = "Failed to create membership."
      render :new
    end
  end

  def membership_params
    params.require(:membership).permit(:name, :sku, :category_id, :price_cents, :days_of_membership)
  end

    def add_or_remove_membership_types
      if params[:action_type] == "add"
        # Logic to add a new membership type
        membership_params = {
          sku: params[:sku],
          name: params[:name],
          category: params[:category],
          price_cents: params[:price_cents],
          days_of_membership: params[:days_of_membership]
        }
        @membership = Membership.new(membership_params)

        if @membership.save
          flash[:success] = "Membership type added successfully."
        else
          flash[:error] = "Failed to add membership type."
        end
      elsif params[:action_type] == "remove"
        # Logic to remove an existing membership type
        membership = Membership.find_by(id: params[:membership_id])
        if membership.present?
          membership.destroy
          flash[:success] = "Membership type removed successfully."
        else
          flash[:error] = "Membership type not found."
        end
      end

      redirect_to admins_show_membership_path

    end


    def add_days
      user = User.find_by(id: params[:user_id])
      membership = Membership.find_by(id: params[:membership_id])

      if user.nil?
        flash[:error] = "User not found."
        redirect_to admins_memberships_show_path and return
      end

      if membership.nil?
        flash[:error] = "Membership not found."
        redirect_to admins_memberships_show_path and return
      end

      days_remaining = user.membership_days || 0
      days_to_modify = 0

      case membership.sku
      when "daily"
        days_to_modify += params[:order_amount].to_i
      when "monthly"
        days_to_modify += params[:order_amount].to_i * 30
      when "yearly"
        days_to_modify += params[:order_amount].to_i * 365
      end

      new_days = if params[:action_type] == "add"
                   days_remaining + days_to_modify
                 elsif params[:action_type] == "subtract"
                   [0, days_remaining - days_to_modify].max
                 else
                   flash[:error] = "Invalid action type."
                   redirect_to admins_memberships_show_path and return
                 end

      membership_log = user.membership_logs.create(
        membership_id: params[:membership_id],
        amount: params[:order_amount].to_i,
        total_cost: params[:total_cost].to_i,
        operation: params[:action_type]
      )

      user.last_membership_start_date = DateTime.now if user.membership_days_remaining == 0
      user.membership_days = new_days

      if user.memberships.exclude?(membership)
        user.memberships << membership
      end

      if user.save
        membership_log.save!
        flash[:success] = "#{days_to_modify} days #{params[:action_type]}ed successfully."
      else
        flash[:error] = "Failed to #{params[:action_type]} days."
      end

      redirect_to admins_show_membership_path(user_id: user.id)
    end




  private

  def sort_column
    params[:sort] || 'username'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    @memberships = Membership.includes(:user)
  end

  def show
    @membership = Membership.find(params[:id])
  end

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/admins/memberships/index.html.erb
<h1>Memberships Index</h1>
<% if @memberships.present? %>
  <% @memberships.each do |membership| %>
    <p>Membership Name: <%= membership.name %></p>
    <p>SKU: <%= membership.sku %></p>
    <p>Category: <%= membership.category.name %></p> <!-- Access category name -->
    <p>Price (in cents): <%= membership.price_cents %></p>
    <p>Days of Membership: <%= membership.days_of_membership %></p>
    <p>Created At: <%= membership.created_at %></p>
    <hr>
  <% end %>
<% else %>
  <p>No memberships found.</p>
<% end %>

app/views/admins/memberships/show.html.erb
<div class="container mx-auto max-w-screen-2xl px-4 py-4 sm:px-6 lg:px-8">
  <section class="shadow-lg bg-white p-6 rounded-lg">
    <div class="flex flex-col rounded-lg border border-red-900 px-4 py-2 text-center mb-8">
      <h1 class="text-2xl text-center py-2 font-bold text-gray-900 sm:text-3xl">Memberships Database</h1>
      <p class="text-gray-500 sm:text-xl">User and Membership Data</p>
    </div>

    <div class="flex flex-col rounded-lg border border-red-900 px-4 py-2 text-center mb-8">
      <h1 class="text-2xl text-center py-2 font-bold text-gray-900 sm:text-3xl">Membership Info</h1>
    </div>
   <div class="overflow-x-auto">
    <table class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
      <thead class="ltr:text-left rtl:text-right">
        <tr>
          <th class="sortable px-4 py-2 font-medium text-gray-900"><%= sort_link('username', 'Username') %></th>
          <th class="sortable px-4 py-2 font-medium text-gray-900"><%= sort_link('last_membership_start_date', 'Updated at') %></th>
          <th class="sortable px-4 py-2 font-medium text-gray-900"><%= sort_link('price', 'Price') %></th>
          <th class="sortable px-4 py-2 font-medium text-gray-900"><%= sort_link('membership_days', 'Membership (days)') %></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <% @users_with_memberships.each do |user| %>
          <tr>
            <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900"><%= user.username %></td>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= user.updated_at %></td>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700">N/A</td>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700" id="membershipDays<%= user.id %>"><%= user.membership_days_remaining %></td>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700">
              <%= button_to "Delete User", admins_user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete #{user.username}?" }, class: "block rounded-lg bg-red-700 px-5 py-3 text-sm font-medium text-white mt-4 mx-auto mb-4" %>
            </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @users_with_memberships%>
  </section>

<section class="shadow-lg bg-white p-6 rounded-lg mt-8">
  <div class="flex flex-col rounded-lg border border-red-900 px-4 py-2 text-center mb-8">
    <h1 class="text-2xl text-center py-2 font-bold text-gray-900 sm:text-3xl">Update a Membership</h1>
  </div>

  <%= form_with(url: add_days_admins_membership_path, method: :post, class: "mt-6 space-y-4 pb-6", multipart: true) do |form| %>
    <div class="grid grid-cols-1 gap-4 p-6">
      <!-- Select dropdown for User ID -->
      <div>
        <%= form.label :user_id, "User ID:", class: "sr-only" %>
        <%= form.select :user_id, User.all.map { |user| [user.username, user.id] }, {}, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm" %>
      </div>

      <!-- Select dropdown for Membership Type -->
      <div>
        <%= form.label :membership_id, "Membership Type:", class: "sr-only" %>
        <%= form.select :membership_id, Membership.all.map { |membership| [membership.name, membership.id] }, {}, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm" %>
      </div>

      <!-- Input field for Order Amount -->
      <div>
        <%= form.label :order_amount, "Order Amount:", class: "sr-only" %>
        <div class="relative">
          <%= form.number_field :order_amount, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm", placeholder: "Total amount" %>
        </div>
      </div>

      <!-- Input field for Total Cost -->
      <div>
        <%= form.label :total_cost, "Total Cost:", class: "sr-only" %>
        <%= form.number_field :total_cost, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm", placeholder: "Enter price" %>
      </div>

      <!-- Select dropdown for Action Type -->
      <div>
        <%= form.label :action_type, "Action:", class: "sr-only" %>
        <%= form.select :action_type, [["Add", "add"], ["Subtract", "subtract"]], {}, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm" %>
      </div>

      <!-- Image Uploader -->
<<<<<<< HEAD
      <!-- <div>
=======
      <!--<div>
>>>>>>> 8ec3d624d6c9a0c12092cb359b977d07c566d7fd
        <%= form.label :photo, "Take Photo:", class: "sr-only" %>
        <div class="flex flex-col items-center">
          <video id="video" width="320" height="240" autoplay class="rounded-lg border-gray-200"></video>
          <button type="button" id="snap" class="mt-2 rounded-lg bg-red-700 px-4 py-2 text-sm font-medium text-white">Snap Photo</button>
          <canvas id="canvas" width="320" height="240" style="display:none;"></canvas>
          <%= form.file_field :photo, id: 'photo-input', accept: 'image/*', style: 'display:none;' %>
        </div>
      </div>
    </div> -->

    <!-- Submit button -->
    <%= form.submit "Submit", class: "block rounded-lg bg-red-700 px-5 py-3 text-sm font-medium text-white mt-4 mx-auto mb-4" %>
  <% end %>
</section>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    console.log("DOM fully loaded and parsed");

    var video = document.getElementById('video');
    var canvas = document.getElementById('canvas');
    var snap = document.getElementById('snap');
    var photoInput = document.getElementById('photo-input');

    console.log("Elements retrieved:", video, canvas, snap, photoInput);

    // Get access to the camera
    if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
      navigator.mediaDevices.getUserMedia({ video: true })
        .then(function(stream) {
          video.srcObject = stream;
          video.play();
          console.log("Camera stream started");
        })
        .catch(function(err) {
          console.error("Error accessing the camera: ", err);
        });
    } else {
      console.error("getUserMedia not supported on your browser!");
    }

    // Trigger photo take
    snap.addEventListener("click", function() {
      console.log("Snap button clicked");

      var context = canvas.getContext('2d');
      context.drawImage(video, 0, 0, 320, 240);
      console.log("Image drawn on canvas");

      canvas.toBlob(function(blob) {
        console.log("Canvas converted to blob");

        var file = new File([blob], "photo.png", { type: 'image/png' });
        var dataTransfer = new DataTransfer();
        dataTransfer.items.add(file);
        photoInput.files = dataTransfer.files;

        console.log("Blob converted to file and assigned to input");
      }, 'image/png');
    });
  });
</script>



  <section class="shadow-lg bg-white p-6 rounded-lg mt-8">
    <div class="flex flex-col rounded-lg border border-red-900 px-4 py-2 text-center mb-8">
      <h1 class="text-2xl text-center py-2 font-bold text-gray-900 sm:text-3xl">Create a New Membership Type</h1>
    </div>
    <%= form_with(model: Membership.new, url: admins_memberships_path, method: :post) do |form| %>
      <div class="grid grid-cols-1 gap-4 p-6">
        <!-- Membership Name -->
        <div>
          <%= form.label :name, "Membership Name:", class: "sr-only" %>
          <%= form.text_field :name, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm", placeholder: "Enter membership name" %>
        </div>

        <!-- SKU -->
        <div>
          <%= form.label :sku, "SKU:", class: "sr-only" %>
          <%= form.text_field :sku, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm", placeholder: "Enter SKU" %>
        </div>

        <!-- Category -->
        <div>
          <%= form.label :category_id, "Category:", class: "sr-only" %>
          <%= form.select :category_id, Category.all.map { |c| [c.name, c.id] }, {}, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm" %>
        </div>

        <!-- Price (in cents) -->
        <div>
          <%= form.label :price_cents, "Price (in cents):", class: "sr-only" %>
          <%= form.number_field :price_cents, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm", placeholder: "Enter price (in cents)" %>
        </div>

        <!-- Days of Membership -->
        <div>
          <%= form.label :days_of_membership, "Days of Membership:", class: "sr-only" %>
          <%= form.number_field :days_of_membership, class: "rounded-lg border-gray-200 p-4 w-full text-sm shadow-sm", placeholder: "Enter number of days" %>
        </div>

        <!-- Submit button -->
        <%= form.submit "Submit", class: "block rounded-lg bg-red-700 px-5 py-3 text-sm font-medium text-white mt-4 mx-auto mb-4" %>
      </div>
    <% end %>
  </section>
</div>